#!/usr/bin/env bash
# Installs nginx and then configures it to listen on port 80
# prints "Hello World" when queried using curl

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo 'Hello World!' > /var/www/html/index.html
sudo nginx restart
