#!/usr/bin/env bash
#Configures a new nginx server to perform a permanent redirect from
#`/redirect_me` to a new web page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me htps://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
